-- Limit public tracking and blockchain verification requests per client/window.
-- Store only an HMAC identifier generated by the application, never the raw IP.
create table if not exists public.public_tracking_rate_limits (
  client_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 1 check (request_count > 0)
);

alter table public.public_tracking_rate_limits enable row level security;
revoke all on public.public_tracking_rate_limits from anon, authenticated;

create or replace function public.take_public_tracking_slot(
  p_client_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_count integer;
begin
  if length(p_client_key) <> 64 or p_limit < 1 or p_window_seconds < 1 then
    return false;
  end if;

  insert into public.public_tracking_rate_limits as limits (client_key, window_started_at, request_count)
  values (p_client_key, now(), 1)
  on conflict (client_key) do update
    set window_started_at = case
      when limits.window_started_at <= now() - (p_window_seconds * interval '1 second') then now()
      else limits.window_started_at
    end,
    request_count = case
      when limits.window_started_at <= now() - (p_window_seconds * interval '1 second') then 1
      else limits.request_count + 1
    end
  returning request_count into next_count;

  return next_count <= p_limit;
end;
$$;

revoke all on function public.take_public_tracking_slot(text, integer, integer) from public, anon, authenticated;
grant execute on function public.take_public_tracking_slot(text, integer, integer) to service_role;
